[package]
name = "docker-command"
version = "0.7.1-alpha.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"
repository = "https://github.com/nicholasbishop/docker-command"
license = "Apache-2.0"
description = "Library for creating Docker commands"
readme = "README.md"
keywords = ["command", "run", "docker", "container", "podman"]

[dependencies]
command-run = "0.13"
users = "0.10"
